name: RTSP Recorder
version: "1.0"
slug: rtsp-recorder
description: Simple RTSP to File recorder with ffmpeg
startup: services
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
schema:
  RTSP_URL: str
  OUTPUT_DIR: str
options:
  RTSP_URL: "rtsp://tapo-cam-06:6Pb05RFaqAG@192.168.178.163:554/stream2"
  OUTPUT_DIR: "/media/Videosorveglianza_Cam06"