name: RTSP Recorder
version: "1.0"
slug: rtsp-recorder
description: Simple RTSP to file recorder using FFmpeg
startup: application
boot: manual
arch:
  - armv7
  - aarch64
  - amd64
  - i386
  - armhf
init: false
host_network: true
map:
  - share:rw
  - config:rw
options:
  rtsp_url: "rtsp://user:pass@camera/stream"
  output_path: "/share/cam_output"
  clip_duration: 60
  retention_days: 7
schema:
  rtsp_url: str
  output_path: str
  clip_duration: int
  retention_days: int
