name: RTSP Recorder
version: "1.0"
slug: rtsp-recorder
description: Simple RTSP to File recorder with ffmpeg
startup: services
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
schema:
  RTSP_URL: str
  OUTPUT_DIR: str
options:
  RTSP_URL: "rtsp://user:pass@camera-ip/stream"
  OUTPUT_DIR: "/media"